# Generated by Django 5.1.3 on 2024-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabmodel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='tab title'),
        ),
    ]
