# Generated by Django 5.1.3 on 2024-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tabmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabmodel',
            name='chats',
        ),
        migrations.AddField(
            model_name='tabmodel',
            name='chats',
            field=models.ManyToManyField(to='base.messagesmodel'),
        ),
    ]
