# Generated by Django 5.1.3 on 2024-11-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_tabmodel_chats_tabmodel_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabmodel',
            name='chats',
            field=models.ManyToManyField(null=True, to='base.messagesmodel'),
        ),
    ]
