# Generated by Django 5.1.3 on 2024-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tabmodel_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabmodel',
            name='chats',
            field=models.ManyToManyField(to='base.messagesmodel'),
        ),
    ]
